[variables]
main_domain = "${domain}"
mysql_root_password = "${password:32}"

[config]
mounts = []

[config.env]
GHOST_HOST="${main_domain}"
DATABASE_ROOT_PASSWORD="${mysql_root_password}"

[[config.domains]]
serviceName = "ghost"
port = 2_368
host = "${main_domain}"
