version: "3.8"

services:
  spacedrive:
    restart: unless-stopped
    image: ghcr.io/spacedriveapp/spacedrive/server:latest
    expose:
      - 8080
    environment:
      - SD_AUTH=${SD_USERNAME}:${SD_PASSWORD}
    volumes:
      - /var/spacedrive:/var/spacedrive
