version: "3.8"
services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - db
    ports:
      - 8000
    volumes:
      - paperless-data:/usr/src/paperless/data
      - paperless-media:/usr/src/paperless/media
      - paperless-export:/usr/src/paperless/export
      - paperless-consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_DBNAME: paperless
      PAPERLESS_URL: https://${domain}
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - paperless-redis-data:/data
  db:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    volumes:
      - paperless-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
volumes:
  paperless-data:
  paperless-media:
  paperless-export:
  paperless-consume:
  paperless-redis-data:
  paperless-pgdata:
