[variables]
main_domain = "${domain}"
admin_user = "admin"
admin_password = "${password}"
db_password = "${password}"
secret_key = "${base64:48}"
timezone = "Etc/UTC"

[config]
[[config.domains]]
serviceName = "paperless-ngx"
port = 8000
host = "${main_domain}"

[config.env]
PAPERLESS_DOMAIN = "${main_domain}"
PAPERLESS_ADMIN_USER = "${admin_user}"
PAPERLESS_ADMIN_PASSWORD = "${admin_password}"
PAPERLESS_DB_PASSWORD = "${db_password}"
PAPERLESS_SECRET_KEY = "${secret_key}"
PAPERLESS_TIME_ZONE = "${timezone}"
