services:
  duplicati:
    image: 'lscr.io/linuxserver/duplicati:latest'
    environment:
      - SERVICE_URL_DUPLICATI_8200
      - PUID=0
      - PGID=0
      - 'TZ=${TZ:-Europe/London}'
      - 'SETTINGS_ENCRYPTION_KEY=${SERVICE_PASSWORD_ENCRYPT}'
      - 'DUPLICATI__WEBSERVICE_PASSWORD=${SERVICE_PASSWORD_WEB}'
    volumes:
      - 'duplicati-config:/config'
      - '/path/to/backups:/backups'
      - '/path/to/source:/source'
      - '/path/to/restore:/restore'

    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8200'
      interval: 2s
      timeout: 10s
      retries: 15

volumes:
  duplicati-config: {}
