services:
  heyform:
    image: heyform/community-edition:latest
    restart: always
    volumes:
      # Persist uploaded images
      - heyform-data:/app/static/upload
    depends_on:
      - mongo
      - redis
    ports:
      - 8000
    env_file:
      - .env
    environment:
      MONGO_URI: 'mongodb://mongo:27017/heyform'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SMTP_FROM: ${SMTP_FROM}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_IGNORE_CERT: ${SMTP_IGNORE_CERT}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

  mongo:
    image: percona/percona-server-mongodb:4.4
    restart: always
    volumes:
      # Persist MongoDB data
      - mongo-data:/data/db

  redis:
    image: redis
    restart: always
    command: "redis-server --appendonly yes"
    volumes:
      # Persist KeyDB data
      - redis-data:/data

volumes:
  heyform-data:
  mongo-data:
  redis-data:
