version: "3.8"

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    expose:
      - "5055"
    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
    volumes:
      - jellyseerr-config:/app/config

volumes:
  jellyseerr-config:
