[variables]
MATOMO_DOMAIN = "${domain}"
DATABASE_ROOT_PASSWORD = "${password:16}"
DATABASE_PASSWORD = "${password:16}"
DATABASE_NAME = "matomo"
DATABASE_USERNAME = "matomo"

[config]
[[config.domains]]
serviceName = "matomo"
port = 80
host = "${MATOMO_DOMAIN}"

[config.env]
DOMAINS = "${MATOMO_DOMAIN}"
DATABASE_ROOT_PASSWORD = "${DATABASE_ROOT_PASSWORD}"
DATABASE_PASSWORD = "${DATABASE_PASSWORD}"
DATABASE_NAME = "${DATABASE_NAME}"
DATABASE_USERNAME = "${DATABASE_USERNAME}"
