[variables]
PORT = "8080"
WS_ENDPOINT = "ws://reef.host:9944"
EVM_RPC_URL = "http://reef.host:8545"
FAUCET_SEED = ""
DEFAULT_AMOUNT = "1"
MAX_AMOUNT = "10"

[[config.domains]]
serviceName = "reef-faucet"
port = 8080
host = "${domain}"
path = "/"

[config.env]
PORT = "8080"
WS_ENDPOINT = "ws://reef.host:9944"
EVM_RPC_URL = "http://reef.host:8545"
FAUCET_SEED = ""
DEFAULT_AMOUNT = "1"
MAX_AMOUNT = "10"
