[variables]
PORT = "8080"
WS_ENDPOINT = "ws://reef.host:9944"
EVM_RPC_URL = "http://reef.host:8545"
FAUCET_SEED = "0x4beb11e380012110b0b072fbb3d8e7455921cf4658de06c33d970be82ccf9ed5"
DEFAULT_AMOUNT = "1"
MAX_AMOUNT = "10"

[[config.domains]]
serviceName = "reef-faucet"
port = 8080
host = "${domain}"
path = "/"

[config.env]
PORT = "8080"
WS_ENDPOINT = "ws://reef.host:9944"
EVM_RPC_URL = "http://reef.host:8545"
FAUCET_SEED = "0x4beb11e380012110b0b072fbb3d8e7455921cf4658de06c33d970be82ccf9ed5"
DEFAULT_AMOUNT = "1"
MAX_AMOUNT = "10"
