version: "3.8"

services:
  go2rtc:
    image: alexxit/go2rtc:latest
    restart: unless-stopped

    # Access to webcam
    devices:
      - /dev/video0:/dev/video0

    expose:
      - 1984        # Web UI
      - 8554        # RTSP
      - 8555        # WebRTC

    environment:
      - TZ=${TZ}

    volumes:
      - go2rtc-config:/config

volumes:
  go2rtc-config: {}
