[variables]
main_domain = "${domain}"
stream_domain = "${domain}"
app_key = "${base64:32}"
browser_stream_secret = "${hash:32}"
pinokio_token = "${hash:32}"

[config]

[[config.domains]]
serviceName = "puppetflow"
port = 8000
host = "${main_domain}"
https = true

[[config.domains]]
serviceName = "stream-server"
port = 6080
host = "${stream_domain}"
https = true

[config.env]
APP_URL = "https://${main_domain}"
APP_KEY = "base64:${app_key}"
BROWSER_STREAM_PUBLIC_URL = "https://${stream_domain}"
BROWSER_STREAM_SECRET = "${browser_stream_secret}"
PINOKIO_TOKEN = "${pinokio_token}"
