version: '3.8'

services:
  weblate:
    image: weblate/weblate:5.16
    environment:
      # Global settings
      WEBLATE_DEBUG: ${WEBLATE_DEBUG}
      WEBLATE_LOGLEVEL: ${WEBLATE_LOGLEVEL}
      WEBLATE_ALLOWED_HOSTS: ${WEBLATE_ALLOWED_HOSTS}
      #WEBLATE_TIME_ZONE: 
      WEBLATE_REQUIRE_LOGIN: ${WEBLATE_REQUIRE_LOGIN}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE}
      WEBLATE_REGISTRATION_OPEN: ${WEBLATE_REGISTRATION_OPEN}
      WEBLATE_SITE_TITLE: ${WEBLATE_SITE_TITLE}
      WEBLATE_SITE_DOMAIN: ${WEBLATE_SITE_DOMAIN}
      # Admin user setup
      WEBLATE_ADMIN_PASSWORD: ${WEBLATE_ADMIN_PASSWORD}
      WEBLATE_ADMIN_EMAIL: ${WEBLATE_ADMIN_EMAIL}
      WEBLATE_ADMIN_NAME: ${WEBLATE_ADMIN_NAME}
      # Email settings
      WEBLATE_EMAIL_HOST: ${WEBLATE_EMAIL_HOST}
      WEBLATE_EMAIL_HOST_USER: ${WEBLATE_EMAIL_HOST_USER}
      WEBLATE_EMAIL_HOST_PASSWORD: ${WEBLATE_EMAIL_HOST_PASSWORD}
      WEBLATE_SERVER_EMAIL: ${WEBLATE_SERVER_EMAIL}
      WEBLATE_DEFAULT_FROM_EMAIL: ${WEBLATE_DEFAULT_FROM_EMAIL}
      # Redis setup
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      # PostgreSQL setup
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      cache:
        condition: service_started
      database:
        condition: service_healthy
    volumes:
      - weblate-data:/app/data
      - weblate-cache:/app/cache
    restart: always
    read_only: true
    tmpfs:
      - /run
      - /tmp
  cache:
    image: valkey/valkey:9.0.3
    volumes:
      - redis-data:/data
    command: [valkey-server, --save, '60', '1', --loglevel, warning]
    restart: always
    read_only: true
  database:
    image: postgres:18-alpine
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  weblate-cache: {}
  weblate-data: {}
  redis-data: {}
  postgres-data: {}
