[variables]
main_domain = "${domain}"
junctio_secret = "${hash:64}"

[config]
mounts = []

[[config.domains]]
serviceName = "junctio"
port = 3000
host = "${main_domain}"

[config.env]
JUNCTIO_SECRET = "${junctio_secret}"
JUNCTIO_BASE_URL = "https://${main_domain}"
JUNCTIO_TRUST_PROXY = "true"
