[variables]
main_domain = "${domain}"
admin_token = "${password:48}"
zip_password = "${password:32}"

[config]
mounts = []

[[config.domains]]
serviceName = "vaultwarden"
port = 80
host = "${main_domain}"

[config.env]
DOMAIN = "https://${main_domain}"
TZ = "UTC"
ADMIN_TOKEN = "${admin_token}"
WEBSOCKET_ENABLED = "true"
SIGNUPS_ALLOWED = "false"
INVITATIONS_ALLOWED = "true"
SHOW_PASSWORD_HINT = "false"
SMTP_HOST = ""
SMTP_FROM = ""
SMTP_PORT = "587"
SMTP_SECURITY = "starttls"
SMTP_USERNAME = ""
SMTP_PASSWORD = ""
R2_ACCESS_KEY_ID = ""
R2_SECRET_ACCESS_KEY = ""
R2_ACCOUNT_ID = ""
R2_BUCKET_NAME = ""
BACKUP_CRON = "0 5 * * *"
BACKUP_KEEP_DAYS = "30"
ZIP_PASSWORD = "${zip_password}"
