version: "3.8"

services:
  code-server:
    image: codercom/code-server:4.121.0
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - code-server-home:/home/coder
      - code-server-config:/home/coder/.config
    environment:
      - PASSWORD=${PASSWORD}
      - TZ=${TZ}
    user: "1000:1000"

volumes:
  code-server-home:
  code-server-config:
