[variables]
monitoring_domain = "nats-monitor.example.com"
websocket_domain = "nats.example.com"
auth_token = "${password:32}"

[[config.domains]]
serviceName = "nats"
port = 8222
host = "${monitoring_domain}"

[[config.domains]]
serviceName = "nats"
port = 8080
host = "${websocket_domain}"

[config.env]
NATS_AUTH_TOKEN = "${auth_token}"

[[config.mounts]]
filePath = "nats.conf"
content = """
http_port: 8222

authorization {
  token: "$NATS_AUTH_TOKEN"
}

websocket {
  port: 8080
  no_tls: true
}
"""
