version: "3.8"

services:
  cloudcommander:
    restart: unless-stopped
    image: coderaiser/cloudcmd:18.5.1
    expose:
      - "80"
    environment:
      - CLOUDCMD_ROOT=/mnt/fs
      - CLOUDCMD_AUTH=true
      - CLOUDCMD_USERNAME=${USERNAME}
      - CLOUDCMD_PASSWORD=${PASSWORD}
    volumes:
      - /root:/root
      - /:/mnt/fs 
