[variables]
<<<<<<< HEAD
admin_password = "${password:32}"

[config]
[[config.domains]]
serviceName = "gotify"
port = 80
host = "${domain}"

[config.env]
GOTIFY_DEFAULTUSER_PASS = "${admin_password}"
=======
main_domain = "${domain}"

[config]
env = {}
mounts = []

[[config.domains]]
serviceName = "gotify"
port = 80
host = "${main_domain}"
>>>>>>> origin/canary
