[variables]
admin_username = "admin"
admin_password = "${password}"
db_password = "${password}"

[config]
[[config.domains]]
serviceName = "miniflux"
port = 8080
host = "${domain}"

[config.env]
MINIFLUX_ADMIN_USERNAME = "${admin_username}"
MINIFLUX_ADMIN_PASSWORD = "${admin_password}"
MINIFLUX_DB_PASSWORD = "${db_password}"
