version: "3.8"
services:
  neko:
    image: "ghcr.io/m1k1o/neko/firefox:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "52000-52100:52000-52100/udp"
    expose:
      - "8080"
