[variables]
PORT = "8545"
NODE_RPC_URL = "ws://ws.reef.host"

[[config.domains]]
serviceName = "reef-eth-rpc"
port = 8545
host = "${domain}"
path = "/"

[[config.domains]]
serviceName = "reef-eth-rpc"
port = 8545
host = "eth.${domain}"
path = "/"

[config.env]
PORT = "8545"
NODE_RPC_URL = "ws://ws.reef.host"
